# 服务端口
server:
  port: 8202

#配置mapper xml文件的路径
mybatis-plus:
  mapper-locations: classpath:com/hg/common/mapper/xml/*.xml

# 服务名
spring:
  application:
    name: service-hosp
  profiles:
    active: dev  # 环境设置：dev、test、prod
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://43.139.96.22:3306/yygh_cmn?&useSSL=false&useUnicode=true&characterEncoding=utf8
    username: root
    password: admin
#返回json的全局时间格式
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
# redis配置
  redis:
    host: 43.139.96.22
    port: 6379
    timeout: 1800000
    database: 0
    #最大阻塞等待时间(负数表示没限制)
    lettuce:
      pool:
        max-wait: -1
        max-active: 20
        max-idle: 5
        min-idle: 0
        time-between-eviction-runs: 10s

##naocs
#  cloud:
#    nacos:
#      discovery:
#        server-addr: 127.0.0.1:8848
##sentinel
#    sentinel:
#      transport:
#        dashboard: http://127.0.0.1:8858
##mongodb
#  data:
#    mongodb:
#      host: 127.0.0.1
#      port: 2701
#      database: ss
#  rabbitmq:
#    host:
#    port:
#    username:
#    password:

#  日志的方式打印sql
logging:
  level:
    com.hg.common.mapper: DEBUG