# 服务端口
server:
  port: 8203

#配置mapper xml文件的路径
mybatis-plus:
  mapper-locations: classpath:com/hg/user/mapper/xml/*.xml

# 服务名
spring:
  application:
    name: service-user
  profiles:
    active: dev  # 环境设置：dev、test、prod
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://43.139.96.22:3306/yygh_user?&useSSL=false&useUnicode=true&characterEncoding=utf8
    username: root
    password: admin
#返回json的全局时间格式
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
#naocs
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
##sentinel
#    sentinel:
#      transport:
#        dashboard: http://127.0.0.1:8858

#  rabbitmq:
#    host:
#    port:
#    username:
#    password:

#  日志的方式打印sql
logging:
  level:
    com.hg.user.mapper: DEBUG