# 服务端口
server:
  port: 8201

#配置mapper xml文件的路径
mybatis-plus:
  mapper-locations: classpath:com/hg/syt/mapper/xml/*.xml

# 服务名
spring:
  application:
    name: service-hosp
  profiles:
    active: dev  # 环境设置：dev、test、prod
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://43.139.96.22:3306/yygh_hosp?&useSSL=false&useUnicode=true&characterEncoding=utf8
    username: root
    password: admin
#返回json的全局时间格式
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  data:
    mongodb:
      uri: mongodb://43.139.96.22/yygh_hosp

#
#  data:
#    mongodb:
#      auto-index-creation: false
#naocs
#  cloud:
#    nacos:
#      discovery:
#        server-addr: 127.0.0.1:8848
##sentinel
#    sentinel:
#      transport:
#        dashboard: http://127.0.0.1:8858

#  rabbitmq:
#    host:
#    port:
#    username:
#    password:

#  日志的方式打印sql
logging:
  level:
    com.hg.syt.mapper: DEBUG
    com.hg.syt.repository: DEBUG